# Generated by Django 3.2.16 on 2023-01-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20230107_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_cart_id',
            new_name='cart_id',
        ),
    ]
